require("config.appearance")
require("config.options")
require("config.binds")
require("config.utils")
require("config.statusline")
require("config.lsp")
require("config.autocmds")
require("config.lazy")
